services:
  - type: web
    name: monte-cafe
    plan: free
    envVars:
      - key: DB_URL
        value: ${DB_URL}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
