services:
  - type: web
    name: monte-cafe
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_URL
        value: ${DB_URL}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}